name: Patch apk and upload asset

on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U
          pip install bs4
      - name: Download WhatsApp apk
        run: |
          python - <<EOF
          import requests
          from bs4 import BeautifulSoup

          whatsapp_html = requests.get(
              "https://www.whatsapp.com/android", headers={"Accept-Language": "en-US"}
          ).text
          soup = BeautifulSoup(whatsapp_html, "html.parser")
          package_link = soup.find(
              "a",
              attrs={
                  "data-ms": '{"creative":"link","creative_detail":"Android_PackageInstaller_Hero_Link"}'
              },
          ).attrs["href"]
          with open("/tmp/WhatsApp.apk", "wb") as f:
              f.write(requests.get(package_link).content)
          EOF
      - name: Patch WhatsApp.apk
        run: python main.py -p /tmp/WhatsApp.apk
      - name: Upload PatchedWhatsApp.apk
        uses: actions/upload-artifact@v2
        with:
          name: PatchedWhatsApp.apk
          path: PatchedWhatsApp.apk

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Download PatchedWhatsApp.apk
        uses: actions/download-artifact@v2
        with:
          name: PatchedWhatsApp.apk
          path: ./
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PatchedWhatsApp.apk
          asset_name: PatchedWhatsApp.apk
          asset_content_type: application/vnd.android.package-archive
