name: release

on:
  release:
    types: [ created ]
  push:
    branches:
      - ci_tests

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U
      - name: Preparing keystore
        id: prepare_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: Preparing the patched apk
        env:
          KEYSTORE_PATH: ${{ steps.prepare_keystore.outputs.filePath }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ls -la
          python main.py